// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <string>

#include "HTP/QnnHtpDevice.h"

#include "core/providers/qnn/builder/qnn_cache_compatibility_manager.h"
#include "core/providers/qnn/builder/qnn_def.h"
#include "core/providers/qnn/builder/qnn_quant_params_wrapper.h"
#include "core/providers/qnn/builder/qnn_utils.h"
#include "core/providers/qnn/htp_usr_drv_utils.h"

namespace onnxruntime {
namespace qnn {

Ort::Status QnnCacheCompatibilityManager::GetCompatibilityInfo(QnnCompatibilityInfo& info) {
  info.backend_id = qnn_backend_manager_->GetBackendId();
  info.backend_api_version = qnn_backend_manager_->GetBackendApiVersion();

  info.htp_arch = static_cast<uint32_t>(qnn_backend_manager_->GetHtpArch());
  RETURN_IF(info.htp_arch == static_cast<uint32_t>(QNN_HTP_DEVICE_ARCH_NONE), "Unable to acquire HTP arch.");

  RETURN_IF_ERROR(htp_usr_drv::IsHtpUsrDrvEnabled(qnn_backend_manager_->GetBackendLibDir(),
                                                  info.htp_arch,
                                                  info.is_htp_usr_drv));

  // There is no way to query HNRD's backend API version with current APIs. Fortunately, since backend API versions are
  // bumped along with SDK verions, adopt SDK versions in HNRD scenarios, which can be extracted from driver's file
  // version. Note that backend API versions are not entirely discarded to align with QNN behavior.
  if (info.is_htp_usr_drv) {
    info.sdk_version = htp_usr_drv::GetHtpUsrDrvVersion();
    RETURN_IF(info.sdk_version.major == 0 && info.sdk_version.minor == 0 && info.sdk_version.patch == 0,
              "Failed to get HtpUsrDrv file version.");
  } else {
    const std::string& sdk_version = qnn_backend_manager_->GetSdkVersion();
    auto split_versions = utils::SplitString(sdk_version, ".");
    RETURN_IF(split_versions.size() != 4 || split_versions[0].substr(0, 1) != "v",
              "Expected SDK version in vMajor.Minor.Patch.BuildId format.");
    info.sdk_version = QnnVersion{static_cast<uint32_t>(std::stoi(std::string(split_versions[0].substr(1)))),
                                  static_cast<uint32_t>(std::stoi(std::string(split_versions[1]))),
                                  static_cast<uint32_t>(std::stoi(std::string(split_versions[2])))};
  }

  return Ort::Status();
}

Ort::Status QnnCacheCompatibilityManager::ValidateCompatibilityInfo(const QnnCompatibilityInfo& info,
                                                                    OrtCompiledModelCompatibility& compatibility) {
  compatibility = OrtCompiledModelCompatibility_EP_NOT_APPLICABLE;

  // Get runtime info to be compared with the given one.
  QnnCompatibilityInfo runtime_info;
  RETURN_IF_ERROR(GetCompatibilityInfo(runtime_info));

  auto is_htp_arch_compatible = [cb_htp_arch = info.htp_arch, rt_htp_arch = runtime_info.htp_arch] {
    if (cb_htp_arch < rt_htp_arch) {
      return OrtCompiledModelCompatibility_EP_SUPPORTED_PREFER_RECOMPILATION;
    } else if (cb_htp_arch == rt_htp_arch) {
      return OrtCompiledModelCompatibility_EP_SUPPORTED_OPTIMAL;
    } else {
      return OrtCompiledModelCompatibility_EP_UNSUPPORTED;
    }
  };

  // The comparison order is as below:
  //   1. backend ID
  //   2. backend API version (if no HNRD involved) / SDK version (if HNRD involved)
  //   3. (Deprecated) context blob version
  //   4. HTP arch
  //
  // Notes:
  //   - Context blob version is deprecated from compatibility info due to the peak memory concern in the previous
  //     approach which acquires the runtime context blob version through creating a fake context binary. Nevertheless,
  //     the removal in fact does not impact the compatibility validation since the combination of a new context binary
  //     generated by an old SDK is impossible. Thus, comparing backend API version / SDK version is enough to cover
  //     context blob version.

  if (info.backend_id != runtime_info.backend_id) {
    compatibility = OrtCompiledModelCompatibility_EP_UNSUPPORTED;
    return Ort::Status();
  }

  // Deliberately leave all branches without reduction for readibility and maintainability.
  if (!info.is_htp_usr_drv && !runtime_info.is_htp_usr_drv) {
    if (info.backend_api_version <= runtime_info.backend_api_version) {
      compatibility = is_htp_arch_compatible();
    } else {
      compatibility = OrtCompiledModelCompatibility_EP_UNSUPPORTED;
    }
  } else if (!info.is_htp_usr_drv && runtime_info.is_htp_usr_drv) {
    if (info.sdk_version <= runtime_info.sdk_version) {
      compatibility = is_htp_arch_compatible();
    } else {
      compatibility = OrtCompiledModelCompatibility_EP_UNSUPPORTED;
    }
  } else if (info.is_htp_usr_drv && !runtime_info.is_htp_usr_drv) {
    // Unexpected usage of context binary generated by user driver path but executing on traditional path.
    compatibility = OrtCompiledModelCompatibility_EP_UNSUPPORTED;
  } else {  // (info.is_htp_usr_drv && runtime_info.is_htp_usr_drv)
    if (info.sdk_version <= runtime_info.sdk_version) {
      compatibility = is_htp_arch_compatible();
    } else {
      compatibility = OrtCompiledModelCompatibility_EP_UNSUPPORTED;
    }
  }

  return Ort::Status();
}

}  // namespace qnn
}  // namespace onnxruntime
