# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MIT

name: "Artifactory Setup"
description: "Prepare JFrog CLI to use Artifactory"

runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        disable-auto-build-publish: true
        disable-job-summary: true
      env:
        JF_URL: ${{ secrets.BUILD_ARTIFACTORY_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.BUILD_ARTIFACTORY_TOKEN }}
