# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MIT

name: Qualcomm Internal Clean Artifacts
description: Periodically impose a retention policy on Artifactory Artifacts

on:
  schedule:
    - cron: "0 8 * * *"  # Every day at 1am in San Diego/PDT (8am UTC)
  workflow_dispatch:
  pull_request:  # TODO-jrk: remove this trigger
    branches: [main]

# only one active job per PR. this will cause jobs to be immediately cancelled on subsequent pushes in PRs.
# ref: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  clean-ci-artifacts:
    name: "Clean temporary CI artifacts"
    runs-on: [self-hosted]

    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          disable-auto-build-publish: true
          disable-job-summary: true
        env:
          JF_URL: ${{ secrets.BUILD_ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.BUILD_ARTIFACTORY_TOKEN }}

      - name: Delete old CI artifacts
        run: >
          jf rt delete --insecure-tls=true
          --spec "${{ github.workspace }}/qcom/scripts/artifactory/aql/expired_ci_artifacts.json"
          --spec-vars "repo=aisw-ortqnnep-generic-virtual"
          --dry-run
