# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MIT

name: Qualcomm Internal PyTest

permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pytest-unit-tests:
    name: PyTest Unit Tests
    runs-on: ["self-hosted", "X64", "Linux", "Build"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Run pytest
        working-directory: qcom/scripts/all/tests
        run: |
          python3 -m venv .venv
          .venv/bin/pip install -r requirements-ci-test.txt
          .venv/bin/python -m pytest -q
