# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MIT

name: Qualcomm Internal Build & Test (ORT HOME)

permissions:
  contents: read
  checks: write

on:
  workflow_call:
    inputs:
      nightly_build:
        type: boolean
        default: true
      target_py_vsn:
        default: "3.12"
        type: string

env:
  ORT_NIGHTLY_BUILD: "${{ inputs.nightly_build == true && '1' || '0' }}"
  BUILD_ARTIFACTORY_REPO: "${{ secrets.BUILD_ARTIFACTORY_REPO }}"

jobs:

  build-ort-home-linux-x86_64:
    uses: ./.github/workflows/qualcomm-internal-build-and-test-single-os.yml
    secrets: inherit
    with:
      nightly_build: ${{ inputs.nightly_build }}
      target_os: linux
      target_arch: x86_64
      target_py_vsn: "3.10"
      use_ort_home: true

  build-ort-home-windows-x86_64:
    uses: ./.github/workflows/qualcomm-internal-build-and-test-single-os.yml
    secrets: inherit
    with:
      nightly_build: ${{ inputs.nightly_build }}
      target_arch: x86_64
      target_py_vsn: ${{ inputs.target_py_vsn }}
      use_ort_home: true
