# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MIT

name: Scheduled Publish of ONNX Runtime Execution Provider

permissions:
  checks: write
  contents: read
  id-token: write

on:
  schedule:
    - cron: "0 9 * * *"  # Every day at 2am in San Diego/PDT (9am UTC)
  workflow_dispatch:
    inputs:
      do_windows_arm64_debug:
        description: "If true, also build Windows ARM64 in Debug configuration."
        type: boolean
        default: false
      do_windows_arm64_relwithdebinfo:
        description: "If true, also build Windows ARM64 in RelWithDebInfo configuration."
        type: boolean
        default: false

jobs:
  publish-artifacts:
    name: Publish Artifacts
    uses: ./.github/workflows/qualcomm-internal-release.yml
    secrets: inherit
    with:
      nightly_build: true
      skip_publish_qa: false
      skip_publish_wheel: false

  publish-artifacts-debug:
    if: ${{ inputs.do_windows_arm64_debug }}
    uses: ./.github/workflows/qualcomm-internal-build-artifacts.yml
    secrets: inherit
    with:
      nightly_build: true
      do_windows_arm64_debug: true

  publish-artifacts-relwithdebinfo:
    if: ${{ inputs.do_windows_arm64_relwithdebinfo }}
    uses: ./.github/workflows/qualcomm-internal-build-artifacts.yml
    secrets: inherit
    with:
      nightly_build: true
      do_windows_arm64_relwithdebinfo: true
