# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MIT

name: "Upload QA Artifact"
description: "Upload a QA artifact to Artifactory"

inputs:
  src_pattern:
    description: Pattern of files to upload, relative to build/
    required: true
    type: string
  qa_tag:
    description: Name of the QA release
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Upload to Artifactory
      shell: "${{ runner.os == 'Windows' && 'cmd' || 'bash' }}"
      run: >
        "${{ runner.os == 'Windows' && 'python.exe' || 'python3' }}"
        qcom/scripts/artifactory/publish_qa.py
        --src-pattern "${{ inputs.src_pattern }}"
        --tag "${{ inputs.qa_tag }}"
